<a href="https://colab.research.google.com/github/Arthi2303A51595/python-for-data-science/blob/main/lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

question--1

In [ ]:
import numpy as np

# Create a 2D NumPy array for student marks (rows: students, columns: subjects)
# Let's assume marks for 5 students in 3 subjects (Math, Science, English)
marks = np.array([
    [85, 78, 92],
    [76, 88, 85],
    [90, 95, 93],
    [66, 70, 72],
    [89, 84, 91]
])

print("Student Marks (Rows: Students, Columns: Subjects):")
print(marks)

# Calculate average, minimum, and maximum marks (overall and per subject)
avg_marks = np.mean(marks, axis=0)  # Average per subject
min_marks = np.min(marks, axis=0)   # Minimum per subject
max_marks = np.max(marks, axis=0)   # Maximum per subject

print("\nAverage Marks (per subject):", avg_marks)
print("Minimum Marks (per subject):", min_marks)
print("Maximum Marks (per subject):", max_marks)

# Use slicing to retrieve marks of specific students
# Get marks of student 2 (index 1)
student2_marks = marks[1]
print("\nMarks of Student 2:", student2_marks)

# Get marks of first 3 students
first_three_students = marks[:3]
print("Marks of First 3 Students:\n", first_three_students)

# Use boolean indexing to find students scoring above 80 in any subject
# Check for any subject > 80
above_80 = marks > 80
students_above_80 = np.any(above_80, axis=1)
print("\nBoolean array for marks > 80:\n", above_80)
print("Students scoring above 80 in any subject:", students_above_80)

students_scores_above_80 = marks[students_above_80]
print("Marks of Students scoring above 80 in any subject:\n", students_scores_above_80)

# Reshape the array to view subject-wise performance (transpose it)
subject_wise = marks.T
print("\nSubject-wise Performance (Rows: Subjects, Columns: Students):")
print(subject_wise)

Student Marks (Rows: Students, Columns: Subjects):
[[85 78 92]
 [76 88 85]
 [90 95 93]
 [66 70 72]
 [89 84 91]]

Average Marks (per subject): [81.2 83.  86.6]
Minimum Marks (per subject): [66 70 72]
Maximum Marks (per subject): [90 95 93]

Marks of Student 2: [76 88 85]
Marks of First 3 Students:
 [[85 78 92]
 [76 88 85]
 [90 95 93]]

Boolean array for marks > 80:
 [[ True False  True]
 [False  True  True]
 [ True  True  True]
 [False False False]
 [ True  True  True]]
Students scoring above 80 in any subject: [ True  True  True False  True]
Marks of Students scoring above 80 in any subject:
 [[85 78 92]
 [76 88 85]
 [90 95 93]
 [89 84 91]]

Subject-wise Performance (Rows: Subjects, Columns: Students):
[[85 76 90 66 89]
 [78 88 95 70 84]
 [92 85 93 72 91]]


question--2

In [ ]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan'],
    'ID': [101, 102, 103, 104, 105],
    'Department': ['HR', 'IT', 'Finance', 'Marketing', 'IT'],
    'Salary': [48000, 52000, 60000, 45000, 75000]
}
df = pd.DataFrame(data)
print("Initial Employee DataFrame:\n", df)
high_earners = df[df['Salary'] > 50000]
print("\nEmployees with Salary > 50,000:\n", high_earners)
sorted_df = df.sort_values(by='Salary', ascending=False)
print("\nDataFrame Sorted by Salary (Descending):\n", sorted_df)
df['Bonus'] = df['Salary'] * 0.10
print("\nDataFrame with Bonus Column:\n", df)
df['Total_Compensation'] = df['Salary'] + df['Bonus']
total_expense = df['Total_Compensation'].sum()
print("\nTotal Salary Expense Including Bonuses: ${:,.2f}".format(total_expense))
csv_filename = "employee_salary_data.csv"
df.to_csv(csv_filename, index=False)
print(f"\nDataFrame saved to CSV file: {csv_filename}")

Initial Employee DataFrame:
       Name   ID Department  Salary
0    Alice  101         HR   48000
1      Bob  102         IT   52000
2  Charlie  103    Finance   60000
3    Diana  104  Marketing   45000
4    Ethan  105         IT   75000

Employees with Salary > 50,000:
       Name   ID Department  Salary
1      Bob  102         IT   52000
2  Charlie  103    Finance   60000
4    Ethan  105         IT   75000

DataFrame Sorted by Salary (Descending):
       Name   ID Department  Salary
4    Ethan  105         IT   75000
2  Charlie  103    Finance   60000
1      Bob  102         IT   52000
0    Alice  101         HR   48000
3    Diana  104  Marketing   45000

DataFrame with Bonus Column:
       Name   ID Department  Salary   Bonus
0    Alice  101         HR   48000  4800.0
1      Bob  102         IT   52000  5200.0
2  Charlie  103    Finance   60000  6000.0
3    Diana  104  Marketing   45000  4500.0
4    Ethan  105         IT   75000  7500.0

Total Salary Expense Including Bonuses: $308